# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"save_obj": "00_core.ipynb",
         "load_obj": "00_core.ipynb",
         "wavelength_range": "00_core.ipynb",
         "calc_area": "00_core.ipynb",
         "normalize": "00_core.ipynb",
         "apply_subplot": "00_core.ipynb",
         "showfig": "00_Fitting.ipynb",
         "log_color_scatter": "00_core.ipynb",
         "series_to_annotation": "00_core.ipynb",
         "cluster_and_plot_scatter": "00_core.ipynb",
         "multi_cluster_and_plot": "00_core.ipynb",
         "PCA_decomposition": "00_core.ipynb",
         "clusterize": "00_core.ipynb",
         "calc_df_grouped_stats": "00_core.ipynb",
         "nir_red_ratio": "00_core.ipynb",
         "linear": "00_core.ipynb",
         "expo": "00_core.ipynb",
         "power": "00_core.ipynb",
         "poly": "00_core.ipynb",
         "nechad": "00_core.ipynb",
         "fit_curve": "00_core.ipynb",
         "calc_errors": "00_core.ipynb",
         "plot_data_and_curve": "00_core.ipynb",
         "fit_and_plot_curve": "00_core.ipynb",
         "delete_rows": "00_Data_Preparation.ipynb",
         "show_rows": "00_Data_Preparation.ipynb",
         "get_bad_measurements": "00_Data_Preparation.ipynb",
         "get_missing_values": "00_Data_Preparation.ipynb",
         "get_negative_values": "00_Data_Preparation.ipynb",
         "get_basins_by_measurements": "00_Data_Preparation.ipynb",
         "filter_basin": "00_Data_Preparation.ipynb",
         "filter_ids": "00_Data_Preparation.ipynb",
         "keep_columns": "00_Data_Preparation.ipynb",
         "resample": "00_Data_Preparation.ipynb",
         "load_and_clean": "00_Data_Preparation.ipynb",
         "publish": "00_Fitting.ipynb",
         "Fit": "00_Fitting.ipynb",
         "DfFit": "00_Fitting.ipynb",
         "MultiFit": "00_Fitting.ipynb",
         "GroupFit": "00_Fitting.ipynb"}

modules = ["core.py",
           "cleaning.py",
           "fitting.py",
           "None.py"]

doc_url = "https://cordmaur.github.io/WaterClassification/"

git_url = "https://github.com/cordmaur/WaterClassification/tree/master/"

def custom_doc_links(name): return None
