# AUTOGENERATED! DO NOT EDIT! File to edit: 00_Data_Preparation.ipynb (unless otherwise specified).

__all__ = ['delete_rows', 'show_rows', 'get_bad_measurements', 'get_missing_values', 'get_negative_values',
           'get_basins_by_measurements', 'filter_basin', 'filter_ids', 'keep_columns', 'resample', 'load_and_clean']

# Cell
import pandas as pd

from .core import *

# Cell
def delete_rows(df, ids):
    "This function cleans the informed ids from the dataframe"
    return df[~df.Id.isin(ids)]

def show_rows(df, ids, columns=None):
    "This function shows only the rows with the informed ids"
    columns = df.columns if columns is None else columns
    return df[df.Id.isin(ids)][columns]

# Cell
def get_bad_measurements(df, bad_flags=['não rodou', 'ruim'], flag_col='320'):
    "Cleans the rows in dataframe df that contains the bad_flags"

    return df[df[flag_col].isin(bad_flags)]['Id'].to_list()

# Cell
def get_missing_values(df, columns):
    "Get rows with missing values in a specified range of wavelengths"

    # get Ids that have missing values between two wavelenghts
    sub_df = df.set_index('Id')[columns]
    sub_df.dropna(axis=0, inplace=True)

    return df[~df.Id.isin(sub_df.index)]['Id'].to_list()

# Cell
def get_negative_values(df, columns):
    "Get rows with negative values in the specified columns. NaN will be considered negative."
    sub_df = df.set_index('Id')[columns]
    negatives = (sub_df<0).any(axis=1)

    return df[negatives]['Id'].to_list()

# Cell
def get_basins_by_measurements(df, min_measurements=3):
    # First, we will get the basins with more than 4 measurements
    basins = df.groupby(by=['Rio/ Bacia']).count()['Id']>=min_measurements
    return basins[basins].index

def filter_basin(df, column, values):
    pass
#     idxs = idxs[idxs==True].index

#     sub_df = df[df['Rio/ Bacia'].isin(idxs)]

#     # then, we will remove measurements by Thiago
#     sub_df = sub_df[~sub_df['Ponto'].str.contains('THIAGO')]

# Cell
def filter_ids(df, column, like_string):
    "Get the ids where the column meets a specific string"
    return df[df[column].str.contains(like_string)]['Id'].to_list()


# Cell
def keep_columns(df, wanted_columns):
    "Keeps the wanted_columns and drop the rest."
    drop_columns = df.columns[~df.columns.isin(wanted_columns)]
    return df.drop(columns=drop_columns)

def resample(df, wavelenghts):
    "Resample the wavelenghts, while keeping the alphanumerical columns."
    alfa_columns = df.columns[~df.columns.str.isdigit()]
    keep_columns = alfa_columns.to_list() + wavelenghts
    return df[keep_columns]


# Cell
def load_and_clean(df, flag_col='320',
                   bad_flags=['não rodou', 'ruim'],
                   wl_range = wavelength_range(375, 940),
                   clean_missing=True,
                   clean_neg=True,
                   clean_SPM_column='SPM',
                   display_ids=10,
                   base_columns=['Id', 'Projeto', 'Ponto', 'Rio/ Bacia', 'DATA', 'SPM']
                  ):
    "Load the CSV and apply the cleaning process accordingly."
    # if df is a string, than load the CSV from disk, otherwise, assume it is the desired dataframe
    if isinstance(df, str):
        df = pd.read_csv(df)

    # cleaning bad measurements
    if flag_col is not None and bad_flags is not None:
        ids = get_bad_measurements(df, bad_flags=bad_flags, flag_col=flag_col)
        print(f'Deleting {len(ids)} rows with bad_flags: {ids[:display_ids]}')
        df = delete_rows(df, ids)

    # cleaning missing values
    if clean_missing:
        ids = get_missing_values(df, wl_range)
        print(f'Deleting {len(ids)} rows with missing values (from {wl_range[0]} to {wl_range[-1]}nm): {ids[:display_ids]}')
        df = delete_rows(df, ids)

    if clean_neg:
        # clean negative values in the wavelength range
        ids = get_negative_values(df, wl_range)
        print(f'Deleting {len(ids)} rows with negative values (from {wl_range[0]} to {wl_range[-1]}nm): {ids[:display_ids]}')
        df = delete_rows(df, ids)

    if clean_SPM_column:
        try:
            ids = get_missing_values(df, clean_SPM_column)
            print(f'Deleting {len(ids)} rows with missing SPM values in {clean_SPM_column}: {ids[:display_ids]}')
            df = delete_rows(df, ids)

        except:
            print(f'Could not find SPM values in {clean_SPM_column}')

    # Drop unwanted columns
    wanted_columns = base_columns + wl_range

    return keep_columns(df, wanted_columns)