# AUTOGENERATED! DO NOT EDIT! File to edit: 00_Data_Preparation.ipynb (unless otherwise specified).

__all__ = ['delete_rows', 'show_rows', 'get_missing_values', 'get_negative_values', 'keep_columns']

# Cell
def delete_rows(df, ids):
    "This function cleans the informed ids from the dataframe"
    return df[~df.Id.isin(ids)]

def show_rows(df, ids, columns=None):
    "This function shows only the rows with the informed ids"
    columns = df.columns if columns is None else columns
    return df[df.Id.isin(ids)][columns]

# Cell
def get_missing_values(df, columns):
    "Get rows with missing values in a specified range of wavelengths"

    # get Ids that have missing values between two wavelenghts
    sub_df = df.set_index('Id')[columns]
    sub_df.dropna(axis=0, inplace=True)

    return df[~df.Id.isin(sub_df.index)]['Id'].to_list()

# Cell
def get_negative_values(df, columns):
    "Get rows with negative values in the specified columns. NaN will be considered negative."
    sub_df = df.set_index('Id')[columns]
    negatives = (sub_df<0).any(axis=1)

    return df[negatives]['Id'].to_list()

# Cell
def keep_columns(df, wanted_columns):
    "Keeps the wanted_columns and drop the rest."
    drop_columns = df.columns[~df.columns.isin(wanted_columns)]
    return df.drop(columns=drop_columns)