# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['showfig', 'calc_df_grouped_stats', 'series_to_annotation']

# Cell
import io
import plotly.io as pio
from IPython.core.display import display, HTML
import pandas as pd

# Cell
def showfig(fig, buttonsToRemove=[]):
    html = io.StringIO()
    buttonsToRemove += ['toggleSpikelines', 'hoverCompareCartesian', 'zoomIn2d',
                        'zoomOut2d', 'autoScale2d', 'hoverClosestCartesian']
    pio.write_html(fig, file=html, auto_open=False,
                   config={'modeBarButtonsToRemove': buttonsToRemove,
                           'displaylogo': False,
                          }
                  )

    display(HTML(data=html.getvalue()))

# Cell
def calc_df_grouped_stats(df, groupby, variables, nameslist, funcslist):
    "Calculate the statistics of a dataframe, grouped by a field, given a list of variables and aggregate \nfunctions"
    stats = pd.DataFrame()

    # convert variables to a list
    variables = [variables] if isinstance(variables, str) else variables

    # loop through the desired statistics
    for name, func in zip(nameslist, funcslist):

        # create the renaming dictionary
        renaming = {var:f'{var}_{name}' for var in variables}

        stats = pd.concat([stats, func(df.groupby(by=groupby))[variables].rename(columns=renaming)], axis=1)

    return stats

# Cell
def series_to_annotation(s):
    "create a formatted annotation string given the series"
    res = ""
    for name, value in s.items():
        res += f'{name}: {round(value,2)} <br>'

    return res