# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['showfig', 'HelloSayer']

# Cell
import io
import plotly.io as pio
from IPython.core.display import display, HTML

# Cell
def showfig(fig, buttonsToRemove=[]):
    html = io.StringIO()
    buttonsToRemove += ['toggleSpikelines', 'hoverCompareCartesian', 'zoomIn2d',
                        'zoomOut2d', 'autoScale2d', 'hoverClosestCartesian']
    pio.write_html(fig, file=html, auto_open=False,
                   config={'modeBarButtonsToRemove': buttonsToRemove,
                           'displaylogo': False,
                          }
                  )

    display(HTML(data=html.getvalue()))

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to
    def say(self):
        "Default method to say something"
        print(self.to)
        say_hello(self.to)