# AUTOGENERATED! DO NOT EDIT! File to edit: 00_Fitting.ipynb (unless otherwise specified).

__all__ = ['Fit', 'MultiFit', 'GroupFit']

# Cell

import io
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

import plotly
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go
from IPython.core.display import display, HTML


import pyarrow

import pandas as pd

from .core import *
from .cleaning import *

from scipy.optimize import curve_fit

from sklearn.metrics import r2_score, mean_squared_error

import math

import parser

import warnings
warnings.filterwarnings('ignore')

# Cell
## To solve convergence problems?
#https://stackoverflow.com/questions/56164659/scipy-curve-fit-do-not-converge-even-if-i-iteratively-change-initial-guess


class Fit:
    available_funcs = ['linear', 'expo', 'power', 'nechad']
    "Class that stores a fitting. It has hooks to original data and fitted parameters."
    def __init__(self, fit_params={}):
        self.fit_params = fit_params

        # Flag the forces the output graphs as HTML for display at github
        self.publish=False
        pass

    def plot_fit(self, ax=None):

        if ax is None: ax = plt

        # plot the scatter
        plt.scatter(self.fit_params['X'], self.fit_params['y'])

    def plotly_fit(self, new_func=None, new_params=None, pts=200):
        fig = px.scatter(x=self.fit_params['X'], y=self.fit_params['y'])

        xs = np.linspace(np.min(self.fit_params['X']), np.max(self.fit_params['X']), pts)

        curve = Fit.apply_func(xs, self.func, self.fit_params['params'])
        fig.add_trace(go.Scatter(x=xs, y=curve, mode='lines', name=self.func.__name__))

        if new_func:
            curve = Fit.apply_func(xs, new_func, new_params)
            fig.add_trace(go.Scatter(x=xs, y=curve, mode='lines', name=new_func.__name__))

        return self.showfig(fig)

    def showfig(self, fig, buttonsToRemove=[]):
        "Converts a plotly figure into a HTML graph and displays it. That is necessary to maintain the interactive functionality of plotly in the jekyll documentation, on Github."
        if self.publish: showfig(fig)
        return fig

    @property
    def func(self): return Fit.get_func(self.fit_params['func'])

    @staticmethod
    def fit_curve_df(df, func, expr_x, expr_y, metrics=['r2', 'rmse', 'SSE']):
        "Fits a function using the dataframe and expressions for X and for Y."
        X = Fit.parse_expr_df(df, expr_x)
        y = Fit.parse_expr_df(df, expr_y)

        fit = Fit.fit_curve(func, X, y, metrics=metrics)
        fit.df = df

        fit.fit_params.update({'ids': df['Id'].to_list(), 'band': expr_x, 'variable': expr_y})

        return fit

    @staticmethod
    def apply_func(x, func, params): return func(x, *params)

    @staticmethod
    def fit_curve(func, X, y, metrics=['r2', 'rmse', 'SSE']):
        "Fits a model (function) to a set of data (X, y). Return the parameters and the errors as a dictionary."
        try:
            popt, pcov = curve_fit(Fit.get_func(func), X, y, check_finite=False,)
            return Fit.test_fit(X, y, func, popt)
        except:
            return Fit()

    @staticmethod
    def get_func(func):
        if isinstance(func, str):
            return getattr(Fit, func)
        else:
            return func

    @staticmethod
    def test_fit(X, y, func, params=[], decimal=4, metrics=['r2', 'rmse', 'SSE']):
        "Compute the predictions, calculate the errors and return in a dictionary. If there is no func, assume X is already the y_hat"
        res = {}
        func = Fit.get_func(func)

        y = np.array(y)
        y_hat = np.array(X) if func is None else func(np.array(X), *params)

        if 'r2' in metrics: res.update({'r2': round(r2_score(y, y_hat), decimal)})
        if 'rmse' in metrics: res.update({'rmse': round(math.sqrt(mean_squared_error(y, y_hat)), decimal)})
        if 'SSE' in metrics: res.update({'SSE': round(((y-y_hat)**2).sum(), decimal)})

        if 'rmsle' in metrics: res.update({'rmsle': round(np.sqrt(np.mean(np.square(np.log1p(y) - np.log1p(y_hat)))))})

        res.update({'func': func.__name__ if func is not None else None,
                    'params': params,
                    'qty': len(X),
                    'X': None if func is None else X,
                    'y': y,
                    'y_hat': y_hat})

        return Fit(fit_params = res)

    @staticmethod
    def parse_expr_df(df, expr):
        "Gets an arbitrary expression using the columns of the dataframe. The band columns should start with the letter b (ex. b865)"
        # if the expression is already a column, return it
        if expr in df.columns:
            return df[expr]

        # otherwise, parse the expression
        else:
            code = parser.expr(expr).compile()

            # create the variables in this context
            for var in code.co_names:
                col_name = var if var in df.columns else var[1:]
                exec(var + " = df[col_name]")

            # evaluate the expression
            return eval(code).rename(expr)

    # default functions to use with fit

    @staticmethod
    def nir_red_ratio(x, a, b):
        return a * np.power(x, b)

    @staticmethod
    def linear(x, a, b): return a*x+b

    @staticmethod
    def expo(x, a, b): return a*10**x+b

    @staticmethod
    def power(x, a, b, c):return a*(x)**(b)+c

    @staticmethod
    def poly(x, a, b, c, d):return a*x**b+c*x+d

    @staticmethod
    def nechad(red, a=610.94, c=0.2324): return a * red / (1 - (red / c))

    def filled(self):
        return 'r2' in self.fit_params.keys()

    def __repr__(self):
        if not self.filled():
            return 'Empty fitting'

        s = f"{self.fit_params['func']} func | "
        for key in ['r2', 'rmse', 'SSE', 'qty', 'params']:
            s += f"{key}: {self.fit_params[key]} "

        return s

# Cell
class MultiFit:
    "Fits several funcs to the variable, using the informed bands, and return a dataframe with the results."
    def __init__(self, df, bands, funcs, variable='SPM'):

        self.fits = []

        for band in bands:
            for func in funcs:
                self.fits.append(Fit.fit_curve_df(df, func, band, variable))

        self.df = df
        self.bands = bands
        self.funcs = funcs

        self.results_vars = ['r2', 'rmse', 'SSE', 'params']

    def get_fit(self, func, band):
        for fit in self.fits:
            if fit.filled():
                if (fit.fit_params['func'] == func) and (fit.fit_params['band'] == band):
                    return fit


    def get_results_df(self):
        results = {}

        for band in self.bands:
            res_func = {}
            for func in self.funcs:
                # fit the function using fit_curve_df (that parses the expressions)
                fit = self.get_fit(func, band)

                for key in self.results_vars:
                    res_func.update({(func, key): fit.fit_params[key] if fit and fit.filled() else None})

            results.update({band: res_func})

        return pd.DataFrame.from_dict(results)


    def get_best_fit(self, metric='r2', criteria='max'):
        "Retrieve the summary of the best fit among the fits within this object"
        fits = self.get_results_df()

        scores = fits.loc[(fits.index.levels[0], metric), :]
        idx_name, band = MultiFit.get_best_score(scores)

        res_df = fits.loc[idx_name[0][0], band[0]]
        return res_df.append(pd.Series({'band': band[0], 'func': idx_name[0][0], 'qty': len(self.df), 'ids': self.df['Id'].to_list()}))

    def get_best_fit_obj(self, metric='r2', criteria='max'):
        "Retrieve the actual best fit object. Uses get_best_fit to decide among the results."
        best_fit = self.get_best_fit(metric=metric, criteria=criteria)

        return self.get_fit(best_fit['func'], best_fit['band'])

    @staticmethod
    def fit_filtered(df, bands, funcs, filter_column, filter_value, thresh=10, variable='SPM', metric='r2', criteria='max'):
        "Filters the dataframe by column value and gets the best fit"

        sub_df = df[df[filter_column] == filter_value]

        if len(sub_df) > thresh:
            return MultiFit(sub_df, bands, funcs)
        else:
            return None


    @staticmethod
    def get_best_score(df, criteria='max', priority_funcs=['linear', 'power', 'nechad', 'expo']):
        "Given a dataframe with scores, get the best combination (function and band), that meets the logic criteria (max or min)"

        # Get the function for the criteria
        criteria = pd.DataFrame.max if criteria=='max' else pd.DataFrame.min

        # Get the lists of indexes and columns of elements that meet the criteria
        idxs, cols = np.where(df == criteria(criteria(df, skipna=True)))

        # If there is more than one result, we have to get the one in the higher function piority
        idxs_names = df.index[idxs]

        # Get the loc of the best solution given the priority functions
        loc = 0
        for func in priority_funcs:
            try:
                loc = idxs_names.get_loc(func)

                # If the function appears more than once, gets the first result
                # TODO: update to work with priority bands combinations
                if isinstance(loc, np.ndarray): loc = np.where(loc == True)[0][0]

                break

            except:
                pass

        idxs = [idxs[loc]] if isinstance(loc, np.int64) else idxs[loc]
        cols = [cols[loc]] if isinstance(loc, np.int64) else cols[loc]
        return df.index[idxs], df.columns[cols]

    def __repr__(self):
        s = f'Multifit class with {len(self.fits)} fits, df with {len(self.df)}rows, bands:{self.bands} funcs{self.funcs} '
        return s


# Cell
import pdb
class GroupFit:
    def __init__(self, df, bands, funcs, group_column, variable='SPM', metric='r2', criteria='max', ignore_none=True, thresh=10):
        "Loop through the unique values of the group_column and perform MultiFits according to bands and functions"

        group_fits = {}

        for group in df[group_column].unique():
            sub_df = df[df[group_column] == group]

            group_fit = MultiFit.fit_filtered(df, bands, funcs, group_column, group,
                                              thresh=thresh, variable=variable, metric=metric, criteria=criteria)

            if ignore_none and (group_fit is not None): group_fits.update({group: group_fit})

        self.df = df
        self.bands = bands
        self.funcs = funcs
        self.group_column = group_column
        self.variable = variable
        self.metric = metric
        self.criteria = criteria
        self.group_fits = group_fits


#         self.results = self.calc_grouped_metric(df, pd.DataFrame.from_dict(results, orient='index'), dic_funcs)

    def get_results(self):
        results = {}

        for group, fit in self.group_fits.items():
            results.update({group: fit.get_best_fit()})
        return pd.DataFrame.from_dict(results, orient='index')

    def get_grouped_results(self):
        results = self.get_results()
        fit = self.calc_grouped_metric_()
        return results.append(pd.Series({key: fit.fit_params[key] for key in ['r2', 'rmse', 'SSE', 'qty', 'ids']}).rename('Overall'))

    def calc_grouped_metric_(self):
        preds = []
        targs = []
        for group_fit in self.group_fits.values():
            fit = group_fit.get_best_fit_obj()
            preds = preds + list(fit.fit_params['y_hat'])
            targs = targs + list(fit.fit_params['y'])

        grouped_metric = Fit.test_fit(preds, targs, func=None)
        grouped_metric.fit_params.update({'ids': self.df['Id'].to_list()})
        return grouped_metric