# AUTOGENERATED! DO NOT EDIT! File to edit: 00_Fitting.ipynb (unless otherwise specified).

__all__ = ['showfig', 'publish', 'Fit', 'DfFit', 'MultiFit', 'GroupFit']

# Cell

import io
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

import plotly
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go
from IPython.core.display import display, HTML


import pyarrow

import pandas as pd

from WaterClassification import core
from WaterClassification import cleaning

from scipy.optimize import curve_fit

from sklearn.metrics import r2_score, mean_squared_error

import math

import parser

import warnings
warnings.filterwarnings('ignore')

publish=True
def showfig(fig): return core.showfig(fig) if publish else fig

# Cell
## To solve convergence problems?
#https://stackoverflow.com/questions/56164659/scipy-curve-fit-do-not-converge-even-if-i-iteratively-change-initial-guess

class Fit:
    "Class that stores a fitting. It has hooks to original data and fitted parameters."

    available_funcs = ['linear', 'expo', 'power', 'nechad']

    def __init__(self, func, X, y, metrics=['r2', 'rmse', 'SSE']):
        "Fits a model (function) to a set of data (X, y). Return the parameters and the errors as a dictionary."

        self.metrics = metrics

        try:
            popt, pcov = curve_fit(Fit.get_func(func), X, y, check_finite=False,)
            self.fit_params = Fit.test_fit(X, y, func, popt, metrics=metrics)

        except:
            self.fit_params = {}


    #################################  FITTING METHODS  #################################
    @staticmethod
    def test_fit(X, y, func, params=[], decimal=4, metrics=['r2', 'rmse', 'SSE']):
        "Compute the predictions, calculate the errors and return in a dictionary. If there is no func, assume X is already the y_hat"
        res = {}

        y_hat = np.array(X) if func is None else Fit.apply_func(np.array(X), func, params)

        if 'r2' in metrics: res.update({'r2': round(r2_score(y, y_hat), decimal)})
        if 'rmse' in metrics: res.update({'rmse': round(math.sqrt(mean_squared_error(y, y_hat)), decimal)})
        if 'SSE' in metrics: res.update({'SSE': round(((y-y_hat)**2).sum(), decimal)})

        if 'rmsle' in metrics: res.update({'rmsle': round(np.sqrt(np.mean(np.square(np.log1p(y) - np.log1p(y_hat)))))})

        res.update({'func': Fit.func_name(func) if func is not None else None,
                    'params': params,
                    'qty': len(X),
                    'X': None if func is None else X,
                    'y': y,
                    'y_hat': y_hat})

        return res

    #################################  GRAPHING METHODS  #################################
    def get_func_trace(self, func, params, pts=200, add_metrics=False):
        "Returns a function trace adjusted to this Fit's X range. Func can be either str or function"
        xs = np.linspace(np.min(self.fit_params['X']), np.max(self.fit_params['X']), pts)
        ys = self.apply_func(xs, func, params)

        txt_metrics = ''
        if add_metrics:
            for metric in self.metrics: txt_metrics += f'{metric}: {self.fit_params[metric]}<br>'

        return go.Scatter(x=xs, y=ys, mode='lines', name=self.get_func(func).__name__, text=f'Params:{params}<br>' + txt_metrics)

    def plot_fit(self, df=None, new_funcs=[], new_params=[], pts=200, fig = None, position=(1, 1), **kwargs):
        "Plots the fit (data and curve). If existing fig is passed, the position parameter indicates where (row, col tuple) it will be placed in a given figure"
        scatter_plot = px.scatter(df, x=self.fit_params['X'], y=self.fit_params['y'], **kwargs)

        fig = scatter_plot if fig is None else core.apply_subplot(fig, scatter_plot, position)

        # Add the original fit trace
        fig.add_trace(self.get_func_trace(self.func, self.fit_params['params'], add_metrics=True), row=position[0], col=position[1])

        for new_func, new_param in zip(new_funcs, new_params):
            fig.add_trace(self.get_func_trace(new_func, new_param), row=position[0], col=position[1])

        return fig

    def get_param(self, param_name, default_value=None): return self.fit_params.get(param_name, default_value)

    #################################  FUNCTION METHODS  #################################
    @property
    def func(self): return Fit.get_func(self.get_param('func'))

    @staticmethod
    def apply_func(x, func, params): return Fit.get_func(func)(x, *params)

    @staticmethod
    def get_func(func): return getattr(Fit, func) if isinstance(func, str) else func

    @staticmethod
    def func_name(func): return Fit.get_func(func).__name__

    @staticmethod
    def nir_red_ratio(x, a, b):
        return a * np.power(x, b)

    @staticmethod
    def linear(x, a, b): return a*x+b

    @staticmethod
    def expo(x, a, b): return a*10**x+b

    @staticmethod
    def power(x, a, b, c):return a*(x)**(b)+c

    @staticmethod
    def poly(x, a, b, c, d):return a*x**b+c*x+d

    @staticmethod
    def nechad(red, a=610.94, c=0.2324): return a * red / (1 - (red / c))

    #################################  OTHER METHODS  #################################
    def filled(self):
        return 'r2' in self.fit_params.keys()

    def __repr__(self):
        if not self.filled():
            return 'Empty fitting'

        s = f"{self.fit_params['func']} func | "
        for key in ['r2', 'rmse', 'SSE', 'qty', 'params']:
            s += f"{key}: {self.fit_params[key]} "

        return s

# Cell
class DfFit(Fit):
    def __init__(self, df, func, expr_x, expr_y, metrics=['r2', 'rmse', 'SSE']):
        "Fits a function using the dataframe and expressions for X and for Y."
        X = DfFit.parse_expr_df(df, expr_x)
        y = DfFit.parse_expr_df(df, expr_y)

        super().__init__(func, X, y, metrics=metrics)

        self.df = df
        self.expr_x = expr_x
        self.expr_y = expr_y

        self.fit_params.update({'ids': df['Id'].to_list(), 'band': expr_x, 'variable': expr_y})

    #################################  GRAPHING METHODS  #################################
    def plot_fit(self, position=(1,1), showlegend=True, **kwargs):

        fig = super().plot_fit(df=self.df, position=position, hover_data=['Id', 'Rio/ Bacia', 'Projeto', 'DATA', 'Ponto'], **kwargs)

        fig.update_xaxes(title_text=self.x_label, row=position[0], col=position[1])
        fig.update_yaxes(title_text=self.y_label, row=position[0], col=position[1])

        fig.update_layout(showlegend=showlegend)

        return fig

    #################################  OTHER METHODS  #################################
    @property
    def title(self): return f'Function {self.func.__name__} on {self.expr_x}'

    @property
    def x_label(self): return f'Band {self.expr_x} nm' if self.expr_x in self.df.columns else f'Expression {self.expr_x}'

    @property
    def y_label(self): return self.expr_y

    @staticmethod
    def parse_expr_df(df, expr):
        "Gets an arbitrary expression using the columns of the dataframe. The band columns should start with the letter b (ex. b865)"
        # if the expression is already a column, return it
        if expr in df.columns:
            return df[expr]

        # otherwise, parse the expression
        else:
            code = parser.expr(expr).compile()

            # create the variables in this context
            for var in code.co_names:
                col_name = var if var in df.columns else var[1:]
                exec(var + " = df[col_name]")

            # evaluate the expression
            return eval(code).rename(expr)



# Cell
class MultiFit:
    "Fits several funcs to the variable/expr_y, using the informed bands/expr_x, and return a dataframe with the results."
    def __init__(self, df, lst_expr_x, funcs, expr_y='SPM'):

        self.fits = []

        for expr_x in lst_expr_x:
            for func in funcs:
                self.fits.append(DfFit(df, func, expr_x, expr_y))

        self.df = df
        self.lst_expr_x = lst_expr_x
        self.lst_funcs = funcs
        self.expr_y = expr_y

        self.results_vars = ['r2', 'rmse', 'SSE', 'params']

    #################################  FITTING METHODS  #################################
    def get_fit(self, func, band):
        if func=='bestfit': return self.get_best_fit_obj(**band)

        for fit in self.fits:
            if fit.filled():
                if (fit.fit_params['func'] == func) and (fit.fit_params['band'] == band):
                    return fit

    @staticmethod
    def fit_filtered(df, bands, funcs, filter_column, filter_value, thresh=10, variable='SPM', metric='r2', criteria='max'):
        "Filters the dataframe by column value and gets the best fit"

        sub_df = df[df[filter_column] == filter_value]

        if len(sub_df) > thresh:
            return MultiFit(sub_df, bands, funcs)
        else:
            return None


    #################################  GRAPHING METHODS  #################################
    def plot_multifit(self, rows, cols, plots, positions, base_height=300, **kwargs):

        titles = [self.get_fit(*plot).title for plot in plots]
#         forlist(map(lambda x: f'Function {x[0]} on band {x[1]}', plots))

        fig = plotly.subplots.make_subplots(rows=rows, cols=cols, subplot_titles=titles)

        for plot, position in zip(plots, positions):
            fit = self.get_fit(*plot)
            fig = fit.plot_fit(fig=fig, position=position, **kwargs)


        fig.update_layout(height=base_height*rows)

        return fig

    def plot_best_fit(self, metric='r2', criteria='max', **kwargs):
        return self.plot_multifit(1, 1, [('bestfit', {'metric': metric, 'criteria': criteria})], positions=[(1,1)], **kwargs)

    #################################  BEST FIT METHODS  #################################
    def get_best_fit(self, metric='r2', criteria='max'):
        "Retrieve the summary of the best fit among the fits within this object"
        fits = self.get_results_df()

        scores = fits.loc[(fits.index.levels[0], metric), :]
        idx_name, band = MultiFit.get_best_score(scores)

        res_df = fits.loc[idx_name[0][0], band[0]]
        return res_df.append(pd.Series({'band': band[0], 'func': idx_name[0][0], 'qty': len(self.df), 'ids': self.df['Id'].to_list()}))

    def get_best_fit_obj(self, metric='r2', criteria='max'):
        "Retrieve the actual best fit object. Uses get_best_fit to decide among the results."
        best_fit = self.get_best_fit(metric=metric, criteria=criteria)

        return self.get_fit(best_fit['func'], best_fit['band'])

    @staticmethod
    def get_best_score(df, criteria='max', priority_funcs=['linear', 'power', 'nechad', 'expo']):
        "Given a dataframe with scores, get the best combination (function and band), that meets the logic criteria (max or min)"

        # Get the function for the criteria
        criteria = pd.DataFrame.max if criteria=='max' else pd.DataFrame.min

        # Get the lists of indexes and columns of elements that meet the criteria
        idxs, cols = np.where(df == criteria(criteria(df, skipna=True)))

        # If there is more than one result, we have to get the one in the higher function piority
        idxs_names = df.index[idxs]

        # Get the loc of the best solution given the priority functions
        loc = 0
        for func in priority_funcs:
            try:
                loc = idxs_names.get_loc(func)

                # If the function appears more than once, gets the first result
                # TODO: update to work with priority bands combinations
                if isinstance(loc, np.ndarray): loc = np.where(loc == True)[0][0]

                break

            except:
                pass

        idxs = [idxs[loc]] if isinstance(loc, np.int64) else idxs[loc]
        cols = [cols[loc]] if isinstance(loc, np.int64) else cols[loc]
        return df.index[idxs], df.columns[cols]

    #################################  OTHER METHODS  #################################
    def get_title(self, metric='r2', criteria='max'):
        best_fit = self.get_best_fit_obj(metric=metric, criteria=criteria)
        return f'func {best_fit.func.__name__} on {best_fit.expr_x}'


    def get_results_df(self):
        results = {}

        for expr_x in self.lst_expr_x:
            res_func = {}
            for func in self.lst_funcs:
                # get the saved fit
                fit = self.get_fit(func, expr_x)

                for key in self.results_vars:
                    res_func.update({(func, key): fit.fit_params[key] if fit and fit.filled() else None})

            results.update({expr_x: res_func})

        return pd.DataFrame.from_dict(results)

    def __repr__(self):
        s = f'Multifit class with {len(self.fits)} fits on variable ({self.expr_y}): df with {len(self.df)} rows, bands:{self.lst_expr_x} funcs{self.lst_funcs} '
        return s


# Cell
import pdb
class GroupFit:
    def __init__(self, df, bands, funcs, group_column, variable='SPM', metric='r2', criteria='max', ignore_none=True, thresh=10):
        "Loop through the unique values of the group_column and for each group, perform MultiFits according to bands and functions"

        group_fits = {}

        for group in df[group_column].unique():
            sub_df = df[df[group_column] == group]

            group_fit = MultiFit.fit_filtered(df, bands, funcs, group_column, group,
                                              thresh=thresh, variable=variable, metric=metric, criteria=criteria)

            if ignore_none and (group_fit is not None): group_fits.update({group: group_fit})

        self.df = df
        self.bands = bands
        self.funcs = funcs
        self.group_column = group_column
        self.variable = variable
        self.metric = metric
        self.criteria = criteria
        self.group_fits = group_fits


#         self.results = self.calc_grouped_metric(df, pd.DataFrame.from_dict(results, orient='index'), dic_funcs)

    def get_results(self):
        "Get the best fitting results for each group and returns as a Pandas Dataframe."
        results = {}

        for group, fit in self.group_fits.items():
            results.update({group: fit.get_best_fit()})
        return pd.DataFrame.from_dict(results, orient='index')

    @staticmethod
    def plot_position(cols, linpos): return (linpos//cols+1, linpos%cols+1)

    def plot_group(self, group, **kwargs):
        group_fit = self.group_fits[group]
        return group_fit.plot_best_fit(metric=self.metric, criteria=self.criteria, **kwargs)

    def plot_groups(self, rows, cols, groups=None, showlegend=True, base_height=300, **kwargs):
        "Plot several groups at once"
        groups = self.group_fits.keys() if groups is None else groups

        titles = [f'{group}: ' + self.group_fits[group].get_title(metric=self.metric, criteria=self.criteria) for group in groups]

        fig = plotly.subplots.make_subplots(rows=rows, cols=cols, subplot_titles=titles)

        for i, group in enumerate(groups):
            group_plot = self.plot_group(group, **kwargs)
            fig = core.apply_subplot(fig, group_plot, self.plot_position(cols, i))

        fig.update_layout(showlegend=showlegend, height=base_height*rows)
        return fig

    def get_grouped_results(self):
        "Adds the overall result (considering all points) to the results table."
        results = self.get_results()
        grouped_metric = self.calc_grouped_metric_()
        return results.append(pd.Series({key: grouped_metric[key] for key in ['r2', 'rmse', 'SSE', 'qty', 'ids']}).rename('Overall'))

    def calc_grouped_metric_(self):
        "Calculates the metrics considering all the best fits in the group and return as a dictionary."
        preds = []
        targs = []
        for group_fit in self.group_fits.values():
            fit = group_fit.get_best_fit_obj()
            preds = preds + list(fit.fit_params['y_hat'])
            targs = targs + list(fit.fit_params['y'])

        grouped_metric = Fit.test_fit(preds, targs, func=None)
        grouped_metric.update({'ids': self.df['Id'].to_list()})
        return grouped_metric

    def __repr__(self):
        s = f'Grouped fitting with {len(self.group_fits)} groups: {list(self.group_fits.keys())}'
        return s